name: Process to Tex and Copy

on:
  workflow_dispatch
jobs:
  maketex:
    name: Converts TEI/XML into Tex
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install Saxon, Ant
      run: |
        apt-get update && apt-get install openjdk-11-jre-headless ant -y --no-install-recommend
        ./dl_saxon.sh
    - name: Convert Files
      run: |
        ant
  copyfile:
    needs: maketex
    runs-on: ubuntu-latest
    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './out/.'
        destination_repo: 'arthur-schnitzler/schnitzler-briefe-tex'
        destination_folder: 'tex'
        user_email: 'peter.andorfer@oeaw.ac.at.com'
        user_name: 'csae8092'
        commit_message: 'copy .tex files'
    - name: remove output folder
      run: |
        rm -rf ./out